import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          toastClassName="!rounded-xl !border !border-gray-200 !shadow-lg !bg-white !text-gray-900 !font-sans"
          bodyClassName="!text-sm !text-gray-600 !font-medium"
          progressClassName="!bg-primary"
          closeButtonClassName="!text-gray-400 hover:!text-gray-600"
        />
      </body>
    </html>
  );
}
